<?php
define(
	"DILL2_SFTP_AUTHENTICATION_METHOD_SSH",
	"SSH");
	
define(
	"DILL2_SFTP_AUTHENTICATION_METHOD_SFTP",
	"SFTP");

define(
	"DILL2_FTPS_AUTHENTICATION_METHOD_FTPS",
	"FTPS");

define(
	"DILL2_FTPS_AUTHENTICATION_METHOD_FTP",
	"FTP");
?>