<?php
define(
	"DILL2_SFTP_AUTHENTICATION_METHOD_SSH",
	"SSH");
	
define(
	"DILL2_SFTP_AUTHENTICATION_METHOD_SFTP",
	"SFTP");

define(
	"DILL2_FTPS_AUTHENTICATION_METHOD_FTPS",
	"FTPS");

define(
	"DILL2_FTPS_AUTHENTICATION_METHOD_FTP",
	"FTP");

define(
	"DILL2_PUBLISH_LIVE_PREVIEW_LIVE",
	"Live");

define(
	"DILL2_PUBLISH_LIVE_PREVIEW_PREVIEW",
	"Preview");
?>