<?php
// Contains IDs the class / view WebsiteProjectSettings_View
define( "DILL2_WXID_WXPANEL", 1 );

define("DILL2_WXID_WXSTATICTEXT_WEBSITETITLE", 2);
define("DILL2_WXID_WXTEXTCTRL_WEBSITETITLE", 3);
define("DILL2_WXID_WXSTATICTEXT_WEBSITETESTSERVER_ADDRESS", 4);
define("DILL2_WXID_WXTEXTCTRL_WEBSITETESTSERVER_ADDRESS", 5);
define("DILL2_WXID_WXSTATICTEXT_WEBSITETESTSERVER_PORT", 6);
define("DILL2_WXID_WXTEXTCTRL_WEBSITETESTSERVER_PORT", 7);

define("DILL2_WXID_WXSTATICTEXT_SFTP_PATH_ON_WEBSERVER", 8);
define("DILL2_WXID_WXTEXTCTRL_SFTP_PATH_ON_WEBSERVER", 9);
define("DILL2_WXID_WXSTATICTEXT_SFTP_WEBSERVER_IP_ADDRESS", 10);
define("DILL2_WXID_WXTEXTCTRL_SFTP_WEBSERVER_IP_ADDRESS", 11);
define("DILL2_WXID_WXSTATICTEXT_SFTP_USERNAME", 12);
define("DILL2_WXID_WXTEXTCTRL_SFTP_USERNAME", 13);
define("DILL2_WXID_WXSTATICTEXT_SFTP_PRIVATEKEY", 14);
define("DILL2_WXID_WXFILEPICKERCTRL_SFTP_PRIVATEKEY", 15);
define("DILL2_WXID_WXSTATICTEXT_SFTP_PASSWORD", 18);
define("DILL2_WXID_WXFILEPICKERCTRL_SFTP_PASSWORD", 19);
define("DILL2_WXID_WXSTATICTEXT_SFTP_AUTHENTICATION_METHOD", 34);
define("DILL2_WXID_WXCHOICE_SFTP_AUTHENTICATION_METHOD", 35);
define("DILL2_WXID_WXSTATICTEXT_SFTP_PUBLICKEY", 36);
define("DILL2_WXID_WXFILEPICKERCTRL_SFTP_PUBLICKEY", 37);
define("DILL2_WXID_WXSTATICTEXT_SFTP_PRIVATEKEY_PASSPHRASE", 38);
define("DILL2_WXID_WXFILEPICKERCTRL_SFTP_PRIVATEKEY_PASSPHRASE", 39);

define("DILL2_WXID_WXNOTEBOOK_PARENT", 20);
define("DILL2_WXID_WXPANEL_GENERAL_SETTINGS", 21);
define("DILL2_WXID_WXPANEL_SFTP_SETTINGS", 22);
define("DILL2_WXID_WXPANEL_FTPS_SETTINGS", 23);

define("DILL2_WXID_WXSTATICTEXT_FTPS_PATH_ON_WEBSERVER", 24);
define("DILL2_WXID_WXTEXTCTRL_FTPS_PATH_ON_WEBSERVER", 25);
define("DILL2_WXID_WXSTATICTEXT_FTPS_WEBSERVER_IP_ADDRESS", 26);
define("DILL2_WXID_WXTEXTCTRL_FTPS_WEBSERVER_IP_ADDRESS", 27);
define("DILL2_WXID_WXSTATICTEXT_FTPS_USERNAME", 28);
define("DILL2_WXID_WXTEXTCTRL_FTPS_USERNAME", 29);
define("DILL2_WXID_WXSTATICTEXT_FTPS_PASSWORD", 30);
define("DILL2_WXID_WXFILEPICKERCTRL_FTPS_PASSWORD", 31);
define("DILL2_WXID_WXSTATICTEXT_FTPS_USE_FTP", 32);
define("DILL2_WXID_WXCHECKBOX_FTPS_USE_FTP", 33);
define("DILL2_WXID_WXSTATICTEXT_FTPS_MODE_PASSIVE", 34);
define("DILL2_WXID_WXCHECKBOX_FTPS_MODE_PASSIVE", 35);
?>