<?php
/*******************************************************************************
Tool:  dill2

File:  dill2/code/constants/wxphp_ids.php

Author:  Jannik Haberbosch

Year: 2014

Info:  This file contains wxID constants for the tool.  Each constants has to
begin with a 'DILL2_WXID_' prefix.  After this, the type of the control for which the
id is used should follow in caps.  After this an underscore follows, which is
followed by the variable name / name of the control, which usually defines its'
purpose.

Example:
	DILL2_WXID_WXFRAME_MAINFRAME for the mainframe of the application.

*******************************************************************************/

// wxDill2Frame.php
define( "DILL2_WXID_WXFRAME_MAINFRAME", 1 );
define( "DILL2_WXID_WXPANEL_MAINFRAME", 2 );
define( "DILL2_WXID_WXSTATICTEXT_VERTICAL_LEFT_WEBSITE_STRUCTURE", 3 );
define( "DILL2_WXID_MAINFRAME_WXDATAVIEWTREECTRL_WEBSITE_STRUCTURE", 4 );
define( "DILL2_WXID_MAINFRAME_WXSTATICTEXT_TEMPLATES", 5 );
define( "DILL2_WXID_MAINFRAME_WXLISTBOX_TEMPLATES", 6 );
define( "DILL2_WXID_MAINFRAME_WXSTATICTEXT_CSSFILES", 7 );
define( "DILL2_WXID_MAINFRAME_WXLISTBOX_CSSFILES", 8 );
define( "DILL2_WXID_MAINFRAME_WXSTATICTEXT_JAVASCRIPTFILES", 9 );
define( "DILL2_WXID_MAINFRAME_WXLISTBOX_JAVASCRIPTFILES", 10 );
define( "DILL2_WXID_MAINFRAME_WXSTATICTEXT_EDITOR", 11 );
define( "DILL2_WXID_MAINFRAME_WXSTYLEDTEXTCTRL_EDITOR", 12 );
define( "DILL2_WXID_MAINFRAME_WXBUTTON_EDITORSAVE", 13 );
define( "DILL2_WXID_MAINFRAME_WXSTATICTEXT_MEDIA", 14 );
define( "DILL2_WXID_MAINFRAME_WXLISTBOX_MEDIA", 15 );
define( "DILL2_WXID_MAINFRAME_WXSTATICTEXT_DOWNLOADS", 16 );
define( "DILL2_WXID_MAINFRAME_WXLISTBOX_DOWNLOADS", 17 );
define( "DILL2_WXID_MAINFRAME_WXMENU_FILE_NEW_PROJECT", 18 );
define( "DILL2_WXID_MAINFRAME_WXMENU_FILE_OPEN_PROJECT", 19 );
define( "DILL2_WXID_MAINFRAME_WXMENU_PROJECT_MANAGE_WEBSITE_STRUCTURE", 20 );
define( "DILL2_WXID_MAINFRAME_WXMENU_PROJECT_MANAGE_TEMPLATES", 21 );
define( "DILL2_WXID_MAINFRAME_WXMENU_PROJECT_MANAGE_CSSFILES", 22 );
define( "DILL2_WXID_MAINFRAME_WXMENU_PROJECT_MANAGE_JSFILES", 23 );
define( "DILL2_WXID_MAINFRAME_WXMENU_PROJECT_MANAGE_MEDIAFILES", 24 );
define( "DILL2_WXID_MAINFRAME_WXMENU_PROJECT_MANAGE_DOWNLOADFILES", 25 );
define( "DILL2_WXID_MAINFRAME_WXMENU_PROJECT_GENERATE_WEBSITE", 26 );
define( "DILL2_WXID_MAINFRAME_WXMENU_PROJECT_START_TESTSERVER", 27 );
define( "DILL2_WXID_MAINFRAME_WXMENU_PROJECT_STOP_TESTSERVER", 28 );
define( "DILL2_WXID_MAINFRAME_WXMENU_OPTIONS_SETTINGS", 29 );
define( "DILL2_WXID_MAINFRAME_WXMENU_HELP_HELP", 30 );
define( "DILL2_WXID_MAINFRAME_WXMENU_HELP_ABOUT", 31 );
define( "DILL2_WXID_WXDIALOG_NEWPROJECT", 32 );
define( "DILL2_WXID_WXDIALOG_MANAGEWEBSITESTRUCTURE", 33 );
define( "DILL2_WXID_WXMANAGETEMPLATESDIALOG", 34 );
define( "DILL2_WXID_WXMANAGECSSFILESDIALOG", 35 );
define( "DILL2_WXID_WXMANAGEJSFILESDIALOG", 36 );
define( "DILL2_WXID_WXMANAGEMEDIAFILESDIALOG", 37 );
define( "DILL2_WXID_WXMANAGEDOWNLOADFILESDIALOG", 38 );
define( "DILL2_WXID_MAINFRAME_WXMENU_PROJECT_WEBSITE_PROJECT_SETTINGS", 39 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG", 40 );
define( "DILL2_WXID_WXMANAGEDILL2SETTINGSDIALOG", 41 );
define( "DILL2_WXID_WXHELPDIALOG", 42 );
define( "DILL2_WXID_MAINFRAME_WXMENU_PROJECT_CREATE_BACKUP", 43 );
define( "DILL2_WXID_MAINFRAME_WXMENU_FILE_IMPORT_BACKUP", 44 );
define( "DILL2_WXID_MAINFRAME_WXMENU_PROJECT_UPLOAD_WEBSITE", 45 );
define( "DILL2_WXID_MAINFRAME_WINDOWSIZE_CHANGED", 46 );
define( "DILL2_WXID_MAINFRAME_WXSTATICTEXT_PICTURE_PREVIEW", 47 );

// wxNewWebsiteProjectDialog.php
define( "DILL2_WXID_WXNEWWEBSITEPROJECTDIALOG_WXPANEL", 1 );
define( "DILL2_WXID_WXNEWWEBSITEPROJECTDIALOG_WXSTATICTEXT_MESSAGE", 2 );
define( "DILL2_WXID_WXNEWWEBSITEPROJECTDIALOG_WXTEXTCTRL_NEWPROJECT", 3 );

// wxManageWebsiteStructureDialog.php
define( "DILL2_WXID_MANAGEWEBSITESTRUCTUREDIALOG_WXPANEL", 1 );
define( "DILL2_WXID_MANAGEWEBSITESTRUCTUREDIALOG_WXDATAVIEWTREECTRL", 2 );
define( "DILL2_WXID_MANAGEWEBSITESTRUCTUREDIALOG_WXBUTTON_ADDELEMENT", 3 );
define( "DILL2_WXID_MANAGEWEBSITESTRUCTUREDIALOG_WXBUTTON_RENAMEELEMENT", 4 );
define( "DILL2_WXID_MANAGEWEBSITESTRUCTUREDIALOG_WXBUTTON_DELETEELEMENT", 5 );
define( "DILL2_WXID_MANAGEWEBSITESTRUCTUREDIALOG_WXBUTTON_MOVEELEMENTUP", 6 );
define( "DILL2_WXID_MANAGEWEBSITESTRUCTUREDIALOG_WXBUTTON_MOVEELEMENTDOWN", 7 );
define( "DILL2_WXID_MANAGEWEBSITESTRUCTUREDIALOG_WXBUTTON_MOVEELEMENTTREE", 8 );
define( "DILL2_WXID_MANAGEWEBSITESTRUCTUREDIALOG_WXBUTTON_RENAMEELEMENT_CHECKBOX_CHANGE_TEMPLATE", 9 );
define( "DILL2_WXID_MANAGEWEBSITESTRUCTUREDIALOG_WXDIALOG_RENAMEELEMENT", 10 );
define( "DILL2_WXID_MANAGEWEBSITESTRUCTUREDIALOG_WXDIALOG_RENAMEELEMENT_WXLISTBOX_TEMPLATE_NAME", 11 );
define( "DILL2_WXID_MANAGEWEBSITESTRUCTUREDIALOG_WXTREECTRL", 12 );

// wxManageTemplatesDialog.php
define( "DILL2_WXID_WXMANAGETEMPLATESDIALOG_PANEL", 1 );
define( "DILL2_WXID_WXMANAGETEMPLATESDIALOG_WXLISTBOX_TEMPLATES", 2 );
define( "DILL2_WXID_WXMANAGETEMPLATESDIALOG_WXBUTTON_ADDTEMPLATE", 3 );
define( "DILL2_WXID_WXMANAGETEMPLATESDIALOG_WXBUTTON_RENAMETEMPLATE", 4 );
define( "DILL2_WXID_WXMANAGETEMPLATESDIALOG_WXBUTTON_DELETETEMPLATE", 5 );
define( "DILL2_WXID_WXMANAGETEMPLATESDIALOG_WXBUTTON_ASSIGNCSSFILES", 6 );
define( "DILL2_WXID_WXMANAGETEMPLATESDIALOG_WXBUTTON_ASSIGNJSFILES", 7 );

// wxManageCSSFilesDialog.php
define( "DILL2_WXID_WXMANAGECSSFILESDIALOG_WXPANEL", 1 );
define( "DILL2_WXID_WXMANAGECSSFILESDIALOG_WXLISTBOX_CSSFILES", 2 );
define( "DILL2_WXID_WXMANAGECSSFILESDIALOG_WXBUTTON_ADDCSSFILE", 3 );
define( "DILL2_WXID_WXMANAGEFILESDIALOG_WXBUTTON_RENAMECSSFILE", 4 );
define( "DILL2_WXID_WXMANAGECSSFILESDIALOG_WXBUTTON_DELETECSSFILE", 5 );

// wxManageJSFilesDialog.php
define( "DILL2_WXID_WXMANAGEJSFILESDIALOG_WXPANEL", 1 );
define( "DILL2_WXID_WXMANAGEJSFILESDIALOG_WXLISTBOX_JSFILES", 2 );
define( "DILL2_WXID_WXMANAGEJSFILESDIALOG_WXBUTTON_ADDJSFILE", 3 );
define( "DILL2_WXID_WXMANAGEJSFILESDIALOG_WXBUTTON_RENAMEJSFILE", 4 );
define( "DILL2_WXID_WXMANAGEJSFILESDIALOG_WXBUTTON_DELETEJSFILE", 5 );

// wxManageMediaFilesDialog.php
define( "DILL2_WXID_WXMANAGEMEDIAFILESDIALOG_WXPANEL", 1 );
define( "DILL2_WXID_WXMANAGEMEDIAFILESDIALOG_WXLISTBOX_MEDIAFILES", 2 );
define( "DILL2_WXID_WXMANAGEMEDIAFILESDIALOG_WXBUTTON_ADDMEDIAFILE", 3 );
define( "DILL2_WXID_WXMANAGEMEDIAFILESDIALOG_WXBUTTON_RENAMEMEDIAFILE", 4 );
define( "DILL2_WXID_WXMANAGEMEDIAFILESDIALOG_WXBUTTON_DELETEMEDIAFILE", 5 );

// wxManageDownloadFilesDialog.php
define( "DILL2_WXID_WXMANAGEDOWNLOADFILESDIALOG_WXPANEL", 1 );
define( "DILL2_WXID_WXMANAGEDOWNLOADFILESDIALOG_WXLISTBOX_DOWNLOADFILES", 2 );
define( "DILL2_WXID_WXMANAGEDOWNLOADFILESDIALOG_WXBUTTON_ADDDOWNLOADFILE", 3 );
define( "DILL2_WXID_WXMANAGEDOWNLOADFILESDIALOG_WXBUTTON_RENAMEDOWNLOADFILE", 4 );
define( "DILL2_WXID_WXMANAGEDOWNLOADFILESDIALOG_WXBUTTON_DELETEDOWNLOADFILE", 5 );

// wxManageWebsiteProjectSettingsDialog.php
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXPANEL", 1 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXSTATICTEXT_WEBSITETITLE", 2 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXTEXTCTRL_WEBSITETITLE", 3 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXSTATICTEXT_WEBSITETESTSERVER_ADDRESS", 4 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXTEXTCTRL_WEBSITETESTSERVER_ADDRESS", 5 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXSTATICTEXT_WEBSITETESTSERVER_PORT", 6 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXTEXTCTRL_WEBSITETESTSERVER_PORT", 7 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXSTATICTEXT_UPLOAD_WEBSITE", 8 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXTEXTCTRL_UPLOAD_WEBSITE", 9 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXSTATICTEXT_WEBSERVER_IP_ADDRESS", 10 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXTEXTCTRL_WEBSERVER_IP_ADDRESS", 11 );
// --> Dill2 v2.0.0 - 02.07.2017, Jannik Haberbosch (JANHAB)
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXSTATICTEXT_USERNAME", 12 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXTEXTCTRL_USERNAME", 13 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXSTATICTEXT_PUBLICKEY", 14 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXTEXTCTRL_PUBLICKEY", 15 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXSTATICTEXT_PRIVATEKEY", 16 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXTEXTCTRL_PRIVATEKEY", 17 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXSTATICTEXT_AUTO_UPLOAD", 18 );
define( "DILL2_WXID_WXMANAGEWEBSITEPROJECTSETTINGSDIALOG_WXCHECKBOX_AUTO_UPLOAD", 19 );
// <-- Dill2 v2.0.0 - 02.07.2017, Jannik Haberbosch (JANHAB)

// wxManageDill2SettingsDialog.php
define( "DILL2_WXID_WXMANAGEDILL2SETTINGSDIALOG_WXPANEL", 1 );

// wxHelpDialog.php
define( "DILL2_WXID_WXHELPDIALOG_WXPANEL", 1 );

// wxDialog for uploading the website.
define( "DILL2_WXID_WXDIALOG_UPLOADWEBSITE", 1 );
?>
